In [83]:
import pandas as pd

In [84]:
fh_sierra = "../src/files/GovDocs/private/GovDocs-Sierra-oclcNos-250122.txt"

In [93]:
sdf = pd.read_csv(fh_sierra, sep="\t", header=1, names=["bibNo", "oclcNo"], dtype={"bibNo": str, "oclcNo": int})

In [94]:
sdf.shape[0]

340217

In [95]:
sdf.head()

        bibNo     oclcNo
0  b195973379  778075920
1  b195973380  778076212
2  b195973392  778076307
3  b195973409  778077130
4  b195973410  778077333

In [96]:
fh_oclc = "../src/files/GovDocs/private/govdocs.govdocsALL_kbart-250123.txt"

In [100]:
odf = pd.read_csv(fh_oclc, sep="\t", header=1, usecols=[24], names=["oclcNo"], dtype={"oclcNo": int})

In [101]:
odf.shape[0]

656037

In [102]:
odf.columns

Index(['oclcNo'], dtype='object')

In [103]:
odf.head()

       oclcNo
0  1332962618
1   741310553
2  1220950915
3   695396923
4   758894667

In [104]:
odf.to_csv("../src/files/GovDocs/private/oclc_set_control_nos.csv", index=False)

In [109]:
both_df = pd.merge(odf, sdf, how="outer", on="oclcNo", indicator=True)

In [110]:
both_df.shape[0]

672613

In [111]:
both_df.head()

   oclcNo bibNo     _merge
0      26   NaN  left_only
1      30   NaN  left_only
2      31   NaN  left_only
3      37   NaN  left_only
4      39   NaN  left_only

In [113]:
both_df.to_csv("../src/files/GovDocs/private/GovDocs-merged-oclcNos-250123.csv", index=False)

In [120]:
# these should be verified, OCLC # could have changed - run via API
sierra_only = both_df[both_df["_merge"] == "right_only"]

In [115]:
sierra_only.shape[0]

16517

In [122]:
sierra_only.to_csv("../src/files/GovDocs/private/GovDocs-only-Sierra-250123.csv", index=False, columns=["oclcNo", "bibNo"])

In [116]:
oclc_only = both_df[both_df["_merge"] == "left_only"]

In [117]:
oclc_only.shape[0]

332329

In [118]:
common = both_df[both_df["_merge"] == "both"]

In [119]:
common.shape[0]

323767

In [81]:
both.head()

      oclcNo       bibNo
0  741310553  b19278514x
1  695396923  b188418842
2  758894667  b193816970
3  722781816  b189818712
4  777018552  b195506753

In [82]:
odf.head()

       oclcNo
0  1332962618
1   741310553
2  1220950915
3   695396923
4   758894667

In [129]:
ver_oclc = pd.read_csv("../src/files/GovDocs/private/GovDocs-only-Sierra-250123-checked.csv", sep="|", header=1, names=["bibNo", "current_oclcNo", "sierra_oclcNo"], dtype={"current_oclcNo": str, "sierra_oclcNo": str})

In [130]:
ver_oclc.shape[0]

16514

In [131]:
ver_oclc.head()

        bibNo current_oclcNo sierra_oclcNo
0  b223927612         851887        851887
1  b223985570         877419        877419
2  b151163029        1503869       1503869
3  b15116504x        1787213       1787213
4  b151165063        1798266       1798266

In [132]:
diff_ver_oclc = ver_oclc[ver_oclc["current_oclcNo"] != ver_oclc["sierra_oclcNo"]]

In [133]:
diff_ver_oclc.shape[0]

3025

In [134]:
diff_ver_oclc.head()

         bibNo current_oclcNo sierra_oclcNo
7   b151162906       15498645       2841407
9   b151678194       14600959       3232526
18  b21739663x       11723555       5635618
25  b212633545        7204651       6755394
38  b158780449        8558056       8650526

In [135]:
diff_ver_oclc.to_csv("../src/files/GovDocs/private/GovDocs-only-Sierra-changed.csv", index=False)

In [137]:
diff_ver_oclc.to_csv("../src/files/GovDocs/private/GovDocs-only-Sierra-changed-barcodes.csv", columns=["bibNo"], index=False)